// LogosKit — Swift surface over the Rust Logos core.
//
// The real API (`LogosClient`, `IncomingMessage`, `LogosError`) is generated by
// UniFFI into `Generated/logos_ffi.swift` (gitignored; produced by
// `scripts/build-ios.sh`). This file exists so the SwiftPM target always has a
// committed source, and to expose a tiny bit of metadata.
//
// EXPERIMENTAL — UNAUDITED. Do not use for real secrets.

public enum LogosKit {
    /// The UniFFI/binding contract version this package was generated against.
    public static let bindingVersion = "0.1.0"
}
